// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Faq: typeof import('./components/app/support/Faq.vue')['default']
    Inquiry: typeof import('./components/app/support/Inquiry.vue')['default']
    Notice: typeof import('./components/app/support/Notice.vue')['default']
    Pagination: typeof import('./components/core/Pagination.vue')['default']
    ProductSpec: typeof import('./components/app/ProductSpec.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VBadge: typeof import('./components/core/data-display/VBadge/VBadge.vue')['default']
    VBreadcrumb: typeof import('./components/core/navigation/VBreadcrumb/VBreadcrumb.vue')['default']
    VCard: typeof import('./components/core/surface/VCard/VCard.vue')['default']
    VFooter: typeof import('./components/app/layout/VFooter.vue')['default']
    VHeader: typeof import('./components/app/layout/VHeader.vue')['default']
  }
}

export {}
